"use client";

import { FormEvent, useEffect, useState } from "react";
import { fieldClassName, primaryButtonClassName } from "./account-shell";
import { getSession, rest } from "../lib/supabase-browser";

type Contact={id:string;contact_type:string;label:string;contact_name:string|null;value:string;note:string|null;is_primary:boolean;visible_to_client:boolean};
type WorkLog={id:string;work_date:string;category:string;title:string;description:string|null;visible_to_client:boolean};

export function CompanyOfficeRecordsPanel({companyId,editable=false}:{companyId:string;editable?:boolean}){
 const [contacts,setContacts]=useState<Contact[]>([]); const [logs,setLogs]=useState<WorkLog[]>([]); const [message,setMessage]=useState(""); const [working,setWorking]=useState("");
 async function load(){const s=getSession();if(!s)return;const [cr,lr]=await Promise.all([rest(`company_contacts?company_id=eq.${companyId}&select=id,contact_type,label,contact_name,value,note,is_primary,visible_to_client&order=is_primary.desc,created_at.asc`,s.access_token),rest(`company_work_logs?company_id=eq.${companyId}&select=id,work_date,category,title,description,visible_to_client&order=work_date.desc,created_at.desc`,s.access_token)]);if(cr.ok)setContacts(await cr.json());if(lr.ok)setLogs(await lr.json());}
 useEffect(()=>{void load();},[companyId]);
 async function addContact(e:FormEvent<HTMLFormElement>){e.preventDefault();const s=getSession();if(!s)return;const f=new FormData(e.currentTarget);try{setWorking("contact");const r=await rest("company_contacts",s.access_token,{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({company_id:companyId,contact_type:String(f.get("type")),label:String(f.get("label")),contact_name:String(f.get("name")||"").trim()||null,value:String(f.get("value")),note:String(f.get("note")||"").trim()||null,is_primary:f.get("primary")==="on",visible_to_client:f.get("visible")==="on",created_by:s.user.id})});if(!r.ok)throw new Error("연락처를 저장하지 못했습니다.");e.currentTarget.reset();await load();}catch(err){setMessage(err instanceof Error?err.message:"저장 중 오류가 발생했습니다.");}finally{setWorking("");}}
 async function addLog(e:FormEvent<HTMLFormElement>){e.preventDefault();const s=getSession();if(!s)return;const f=new FormData(e.currentTarget);try{setWorking("log");const r=await rest("company_work_logs",s.access_token,{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({company_id:companyId,work_date:String(f.get("date")),category:String(f.get("category")),title:String(f.get("title")),description:String(f.get("description")||"").trim()||null,visible_to_client:f.get("visible")==="on",created_by:s.user.id})});if(!r.ok)throw new Error("업무로그를 저장하지 못했습니다.");e.currentTarget.reset();await load();}catch(err){setMessage(err instanceof Error?err.message:"저장 중 오류가 발생했습니다.");}finally{setWorking("");}}
 return <section className="rounded-2xl border border-stone-200 bg-white p-5">
  <div><p className="text-xs font-bold tracking-[0.14em] text-emerald-800">OFFICE RECORD</p><h2 className="mt-1 text-lg font-extrabold">연락처 · 우리 사무실 처리업무</h2><p className="mt-1 text-sm text-stone-500">회사와 연결된 연락수단과 숲 법무사 사무소에서 실제 처리한 업무 이력을 관리합니다.</p></div>
  {message&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{message}</p>}
  <div className="mt-6 grid gap-6 lg:grid-cols-2">
   <div><h3 className="font-extrabold">연결 연락처</h3><div className="mt-3 grid gap-2">{contacts.length?contacts.map(c=><div key={c.id} className="rounded-xl border border-stone-200 p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{c.label}{c.is_primary?" · 대표":""}</p><p className="mt-1 text-sm text-stone-700">{c.contact_name?`${c.contact_name} · `:""}{c.value}</p></div><span className="text-xs font-semibold text-stone-400">{c.contact_type}</span></div>{c.note&&<p className="mt-2 text-xs text-stone-500">{c.note}</p>}</div>):<p className="rounded-xl bg-stone-50 p-4 text-sm text-stone-500">등록된 연락처가 없습니다.</p>}</div></div>
   <div><h3 className="font-extrabold">업무 로그</h3><div className="mt-3 grid gap-2">{logs.length?logs.map(l=><div key={l.id} className="rounded-xl border border-stone-200 p-4"><div className="flex justify-between gap-3"><div><p className="font-bold">{l.title}</p><p className="mt-1 text-xs text-stone-500">{l.work_date} · {l.category}</p></div></div>{l.description&&<p className="mt-2 text-sm leading-6 text-stone-600">{l.description}</p>}</div>):<p className="rounded-xl bg-stone-50 p-4 text-sm text-stone-500">등록된 처리업무가 없습니다.</p>}</div></div>
  </div>
  {editable&&<div className="mt-8 grid gap-6 border-t border-stone-200 pt-6 lg:grid-cols-2">
   <form onSubmit={addContact} className="grid gap-3"><h3 className="font-extrabold">연락처 추가</h3><select name="type" className={fieldClassName} defaultValue="email"><option value="email">이메일</option><option value="phone">전화</option><option value="mobile">휴대전화</option><option value="fax">팩스</option><option value="website">웹사이트</option><option value="other">기타</option></select><input name="label" required className={fieldClassName} placeholder="예: 대표 이메일, 등기 담당자"/><input name="name" className={fieldClassName} placeholder="담당자명(선택)"/><input name="value" required className={fieldClassName} placeholder="메일주소 또는 연락처"/><input name="note" className={fieldClassName} placeholder="메모(선택)"/><label className="text-sm"><input name="primary" type="checkbox"/> 대표 연락처</label><label className="text-sm"><input name="visible" type="checkbox" defaultChecked/> 회원에게 표시</label><button disabled={working==="contact"} className={primaryButtonClassName}>연락처 저장</button></form>
   <form onSubmit={addLog} className="grid gap-3"><h3 className="font-extrabold">우리 사무실 처리업무 추가</h3><input name="date" required type="date" className={fieldClassName}/><select name="category" className={fieldClassName} defaultValue="법인등기"><option>법인등기</option><option>부동산등기</option><option>민사서류</option><option>집행</option><option>상담</option><option>기타</option></select><input name="title" required className={fieldClassName} placeholder="예: 임원변경등기 완료"/><textarea name="description" rows={4} className={fieldClassName} placeholder="처리 내용 및 특이사항"/><label className="text-sm"><input name="visible" type="checkbox" defaultChecked/> 회원에게 표시</label><button disabled={working==="log"} className={primaryButtonClassName}>업무로그 저장</button></form>
  </div>}
 </section>;
}